# appveyor.yml
---
image:
  - Visual Studio 2019
  - Ubuntu

build: off

install:
  - sh: sudo apt-get install python-wxgtk3.0
  - sh: pip3 install -r requirements

test_script:
  - sh: bash make_linux.sh
