# appveyor.yml
---
image:
  - Ubuntu
  - Visual Studio 2019

environment:
    PY_DIR: C:\Python36
    PYTHONIOENCODING: utf_8
    PIPENV_IGNORE_VIRTUALENVS: 1
    KEY_PACK_SECRET:
      secure: ybUuwsKZRNlTXAcoY82JYA==
    KEY_PACK_SALT:
      secure: lyep0eVd6GHFcxfNu45Cmvy8SgKaShvCrlr1vpMj8LFs3g4WfM/KPbGtpld77xcTCUu028u5zbFYw+8N11G6Gw==
    

version: '1.0.{build}'
build: off

stack: Python 3.6

init:
    - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
    - cmd: python -m pip install pipenv
    - sh: sudo apt-get -y update
    - sh: sudo apt-get -y install python3-pip python3.6-dev debhelper devscripts debhelper devscripts p7zip-full libssl-dev dpkg-dev build-essential libjpeg-dev libtiff-dev libsdl2-dev libnotify-dev freeglut3 ibus-gtk3 xvfb libhunspell-dev tree
    

install:
  - cmd: appveyor-tools\secure-file -decrypt keypack.pyu.enc -secret %KEY_PACK_SECRET% -salt %KEY_PACK_SALT%
  - sh: ./appveyor-tools/secure-file -decrypt keypack.pyu.enc -secret $KEY_PACK_SECRET -salt $KEY_PACK_SALT
  - pip3 install --upgrade 'setuptools<45.0'
  - sh: pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython
  - cmd: pip3 install -U wxPython 
  - pip3 install -r requirements.txt
  - pyupdater keys -i keypack.pyu

test_script:
  - sh: export PYTHONPATH=/home/appveyor/venv3.6
  - sh: pyupdater build -D --pyinstaller-log-info --app-version $APPVEYOR_BUILD_VERSION linux.spec
  - sh: cat .pyupdater/work/linux/warn-linux.txt
  - cmd: pyupdater build -D --pyinstaller-log-info --app-version %APPVEYOR_BUILD_VERSION% windows.spec
  - cmd: type .pyupdater\work\windows\warn-windows.txt
  - pyupdater pkg -p -s

artifacts:
  - path: 'pyu-data/deploy/*'
  
deploy:
  - provider: GitHub
    draft: true
    auth_token:
      secure: SNbO+xcQuYFq0TbfrCdtFM8iXqREdd3yw7TH9Gw+IoeKWOcRl5BaydJkHmx2YMpz
    on:
      branch: master
  

