# appveyor.yml
---
image:
  - Ubuntu
  - Visual Studio 2019

environment:
    PY_DIR: C:\Python36
    PYTHONIOENCODING: utf_8
    PIPENV_IGNORE_VIRTUALENVS: 1
    KEY_PACK_SECRET:
      secure: ybUuwsKZRNlTXAcoY82JYA==
    KEY_PACK_SALT:
      secure: lyep0eVd6GHFcxfNu45Cmvy8SgKaShvCrlr1vpMj8LFs3g4WfM/KPbGtpld77xcTCUu028u5zbFYw+8N11G6Gw==
    PYU_SSH_USERNAME:
      secure: yKuHQM7+3bA45Fd4jGnv4g==
    PYU_SSH_PASSWORD:
      secure: RPIoVHJYTVd/HiOrF5+kxg==
    PYU_SSH_HOST: phil.mcunderwood.org
    PYU_SSH_REMOTE_PATH: /home/furbrain/webapps/phil_htdocs/releases
    APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkq+bXuZPxcUDCjDBF8KhNLFwhQz5rwoAwl5xUaKPjNnA3Cjt5g0EH6g/NPETlC/C9SDWNUX0Oq0nUIMwz5rnwQnyJRTYNHfkvvBdgW+piVEKq8SiVI6hsnFGGLgm02LuRw2mIu/HEKnCpESw1xSgB3z1zyw+8/WJ5bfL9A6Eeyky4ORy133tX5O6WvMab4eIc22ERq5Mnjul+i5frprOoGaKj9ss8keULQU1H0BYW91KouOXf3R25f4uajEChTYtVh8yxeMZtrmXLZ46+gtC0Zd70bc81erdMS1FMhftoXcaoXXPquRq0A69plViH9/UMG9dZtxziQKUYAi2k83zhmtjpOkZP9u+RV2THybJ7dAZQSIjRdgceWdnjASUC56GCg8AIwvXGvA/LoogCIgLnncLfc6o9ESUsMwz2KlNoWYgTKzHqgPMJ8KmFe6CP7U1cm7zg3/pyflrrXc2gMHKyUpW7gdpkOZs207UYOzNnWb7bBr/osMGwWQ8uCfPIiu4v1uWu1skkVWUDfiUNCDpAPQ/cNJ7feiiRg3WMXEMM79eIJP+gZ4bgwxxefQj0fkFpLJIplpznr6TJsYlfNJ74g3XrfSQv0SnUzIhDTH1qOHe6ut8X0WXjSb7hEIjH/8ndbUp6T8zEVBkzViFHpPfBUpAZnaNoNrJfcNi+B1qlCQ==
version: '1.0.{build}'
build: off

stack: Python 3.6

init:
    - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
    - cmd: python -m pip install pipenv
    - sh: sudo apt-get -y update
    - sh: sudo apt-get -y install python3.6-dev xvfb libhunspell-dev upx-ucl
    

install:
  - cmd: appveyor-tools\secure-file -decrypt keypack.pyu.enc -secret %KEY_PACK_SECRET% -salt %KEY_PACK_SALT%
  - sh: ./appveyor-tools/secure-file -decrypt keypack.pyu.enc -secret $KEY_PACK_SECRET -salt $KEY_PACK_SALT
  - pip3 install --upgrade 'setuptools<45.0'
  - sh: pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython
  - cmd: pip3 install -U wxPython 
  - pip3 install -r requirements.txt
  - python get_versions.py
  - pyupdater keys -i keypack.pyu

test_script:
  - sh: export PYTHONPATH=/home/appveyor/venv3.6
  - sh: pyupdater build --app-version ${APPVEYOR_BUILD_VERSION} linux.spec
  - cmd: pyinstaller windows.spec
  - sh: tar xzvf pyu-data/new/PonyTrainer*.* -C dist/
  - sh: mv dist/PonyTrainer dist/PonyTrainer.run
  - cmd: move dist\win.exe dist\PonyTrainer.exe
  - pyupdater pkg -p -s
  - pyupdater upload --service scp

artifacts:
  - path: 'dist/*.exe'
  - path: 'dist/*.run'
  
deploy:
  - provider: GitHub
    draft: true
    auth_token:
      secure: SNbO+xcQuYFq0TbfrCdtFM8iXqREdd3yw7TH9Gw+IoeKWOcRl5BaydJkHmx2YMpz
    on:
      branch: master

#on_finish:
#  - sh: export APPVEYOR_SSH_BLOCK=true
#  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
